application: thisisfromthesun
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css

- url: /admin
  script: kuploader.application
  secure: always
  login: admin

- url: /.*
  script: kuploader.application
  secure: always
  login: required

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
